### ISSUE TITLE
TypeError: message.id is not a function

### ISSUE THREAD

**Issue by ParsonsProjects** [asyncapi/asyncapi-react#748]
**Description**

It looks like the latest changes from https://github.com/asyncapi/asyncapi-react/commit/eabba4fb52741b529e9b71a82dfd303cb56c69c1#diff-ab2dcbe79ad45d341a8591fc20c2b9896235a440f5465b1b8d165b8c733b9a32L62 have caused a breaking change.

When running `npx asyncapi generate fromTemplate asyncapi.yml @asyncapi/html-template -o ./asyncapi --force-write`

The following error is show:

```
TypeError: message.id is not a function
    at C:\Users\alan_\Work\Projects\craftsman-serverless-api\node_modules\@asyncapi\generator\node_modules\@asyncapi\react-component\src\containers\Sidebar\Sidebar.tsx:51:64
    at Array.map (<anonymous>)
    at Sidebar (C:\Users\alan_\Work\Projects\craftsman-serverless-api\node_modules\@asyncapi\generator\node_modules\@asyncapi\react-component\src\containers\Sidebar\Sidebar.tsx:44:35) 
    at processChild (C:\Users\alan_\Work\Projects\craftsman-serverless-api\node_modules\@asyncapi\generator\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)    
    at resolve (C:\Users\alan_\Work\Projects\craftsman-serverless-api\node_modules\@asyncapi\generator\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Users\alan_\Work\Projects\craftsman-serverless-api\node_modules\@asyncapi\generator\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Users\alan_\Work\Projects\craftsman-serverless-api\node_modules\@asyncapi\generator\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToString (C:\Users\alan_\Work\Projects\craftsman-serverless-api\node_modules\@asyncapi\generator\node_modules\react-dom\cjs\react-dom-server.node.development.js:4298:27)
    at Context.renderSpec (C:\Users\alan_\Work\Projects\craftsman-serverless-api\node_modules\@asyncapi\generator\node_modules\@asyncapi\html-template\filters\all.js:165:25)
    at eval (eval at _compile (C:\Users\alan_\Work\Projects\craftsman-serverless-api\node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:527:18), <anonymous>:38:97)
    at Context.generateBase64Favicon (C:\Users\alan_\Work\Projects\craftsman-serverless-api\node_modules\@asyncapi\generator\node_modules\@asyncapi\html-template\filters\all.js:105:12)
    at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\alan_\Work\Projects\craftsman-serverless-api\node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:527:18), <anonymous>:21:40)
    at Template.render (C:\Users\alan_\Work\Projects\craftsman-serverless-api\node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:454:10)
    at Environment.renderString (C:\Users\alan_\Work\Projects\craftsman-serverless-api\node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:313:17)
    at C:\Users\alan_\Work\Projects\craftsman-serverless-api\node_modules\@asyncapi\generator\lib\renderer\nunjucks.js:32:14
    at new Promise (<anonymous>)
```

**Expected result**
No error is thrown.

**Actual result**
Error is being thrown and stops output.

**Steps to reproduce**
- Install the latest version of @asyncapi/cli
- Run the command `npx asyncapi generate fromTemplate asyncapi.yml @asyncapi/html-template -o ./asyncapi --force-write`

**Troubleshooting**
Tried installing a previous version of the package using the override option with my root package file but this does not seem to take.

**Comment by djohs** [comment]
we are encountering the same error since today using the docker generator image

**Comment by ParsonsProjects** [comment]
I have found a way round this to force the @asyncapi/html-template to 0.20.0 before the @asyncapi/react-components next package is referenced.

`npx asyncapi generate fromTemplate asyncapi.yml @asyncapi/html-template@0.20.0 -o ./asyncapi --force-write`

**Comment by jonaslagoni** [comment]
Duplicate of https://github.com/asyncapi/html-template/issues/438

If you personally integrate with this library and parse your AsyncAPI documents before passing them to the library (i.e. use the bundled component without the parser) make sure to use at least [v3.0.0-next-major-spec.1](https://github.com/asyncapi/parser-js/releases/tag/v3.0.0-next-major-spec.1).

**Comment by jonaslagoni** [comment]
Should be fixed as of [html-template v0.28.4](https://github.com/asyncapi/html-template/releases/tag/v0.28.4)

**Comment by M3lkior** [comment]
Thanks for the rapid fix @jonaslagoni !

**Comment by Pakisan** [comment]
@jonaslagoni not sure, but looks like similar problem after update to 49

log
```
[Error] TypeError: e.dependencies is not a function. (In 'e.dependencies()', 'e.dependencies' is undefined) — resources:32:1883716
	ia (resources:32:539997)
	(anonymous function) (resources:32:546718)
	mo (resources:32:506203)
	pa (resources:32:541312)
	Sc (resources:32:558539)
	Sc
	(anonymous function) (resources:32:591182)
	xc (resources:32:555198)
	fc (resources:32:551503)
	fc
	(anonymous function) (resources:32:502963)
	(anonymous function) (resources:32:591182)
	Ji (resources:32:502909)
	Wi (resources:32:502844)
	cc (resources:32:548073)
	enqueueSetState (resources:32:506627)
	(anonymous function) (resources:32:575238)
	(anonymous function) (resources:32:1992597)
	(anonymous function) (resources:32:1991408)
	s (resources:32:1990250)
[Error] TypeError: e.dependencies is not a function. (In 'e.dependencies()', 'e.dependencies' is undefined) — resources:32:1883716
	ia (resources:32:539997)
	(anonymous function) (resources:32:546718)
	mo (resources:32:506203)
	pa (resources:32:541312)
	Sc (resources:32:558539)
	Sc
	(anonymous function) (resources:32:591182)
	xc (resources:32:555198)
	fc (resources:32:551503)
	fc
	(anonymous function) (resources:32:502963)
	(anonymous function) (resources:32:591182)
	Ji (resources:32:502909)
	Wi (resources:32:502844)
	cc (resources:32:548073)
	enqueueSetState (resources:32:506627)
	(anonymous function) (resources:32:575238)
	(anonymous function) (resources:32:1992597)
	(anonymous function) (resources:32:1991408)
	s (resources:32:1990250)
[Error] TypeError: n.title is not a function. (In 'n.title()', 'n.title' is undefined) — resources:32:1909096
	ia (resources:32:539997)
	(anonymous function) (resources:32:546718)
	mo (resources:32:506203)
	pa (resources:32:541312)
	Sc (resources:32:558539)
	Sc
	(anonymous function) (resources:32:591182)
	xc (resources:32:555198)
	fc (resources:32:551503)
	fc
	(anonymous function) (resources:32:502963)
	(anonymous function) (resources:32:591182)
	Ji (resources:32:502909)
	Wi (resources:32:502844)
	cc (resources:32:548073)
	enqueueSetState (resources:32:506627)
	(anonymous function) (resources:32:575238)
	(anonymous function) (resources:32:1992597)
	(anonymous function) (resources:32:1991408)
	s (resources:32:1990250)
[Error] TypeError: n.title is not a function. (In 'n.title()', 'n.title' is undefined) — resources:32:1909096
	ia (resources:32:539997)
	(anonymous function) (resources:32:546718)
	mo (resources:32:506203)
	pa (resources:32:541312)
	Sc (resources:32:558539)
	Sc
	(anonymous function) (resources:32:591182)
	xc (resources:32:555198)
	fc (resources:32:551503)
	fc
	(anonymous function) (resources:32:502963)
	(anonymous function) (resources:32:591182)
	Ji (resources:32:502909)
	Wi (resources:32:502844)
	cc (resources:32:548073)
	enqueueSetState (resources:32:506627)
	(anonymous function) (resources:32:575238)
	(anonymous function) (resources:32:1992597)
	(anonymous function) (resources:32:1991408)
	s (resources:32:1990250)
[Error] TypeError: o.isSend is not a function. (In 'o.isSend()', 'o.isSend' is undefined) — resources:32:1916241
	ia (resources:32:539997)
	(anonymous function) (resources:32:546718)
	mo (resources:32:506203)
	pa (resources:32:541312)
	Sc (resources:32:558539)
	Sc
	(anonymous function) (resources:32:591182)
	xc (resources:32:555198)
	fc (resources:32:551503)
	fc
	(anonymous function) (resources:32:502963)
	(anonymous function) (resources:32:591182)
	Ji (resources:32:502909)
	Wi (resources:32:502844)
	cc (resources:32:548073)
	enqueueSetState (resources:32:506627)
	(anonymous function) (resources:32:575238)
	(anonymous function) (resources:32:1992597)
	(anonymous function) (resources:32:1991408)
	s (resources:32:1990250)
[Error] TypeError: r.variables is not a function. (In 'r.variables()', 'r.variables' is undefined) — resources:32:1896546
	ia (resources:32:539997)
	(anonymous function) (resources:32:546718)
	mo (resources:32:506203)
	pa (resources:32:541312)
	Sc (resources:32:558539)
	Sc
	(anonymous function) (resources:32:591182)
	xc (resources:32:555198)
	fc (resources:32:551503)
	fc
	(anonymous function) (resources:32:502963)
	(anonymous function) (resources:32:591182)
	Ji (resources:32:502909)
	Wi (resources:32:502844)
	cc (resources:32:548073)
	enqueueSetState (resources:32:506627)
	(anonymous function) (resources:32:575238)
	(anonymous function) (resources:32:1992597)
	(anonymous function) (resources:32:1991408)
	s (resources:32:1990250)
[Error] TypeError: r.variables is not a function. (In 'r.variables()', 'r.variables' is undefined) — resources:32:1896546
	ia (resources:32:539997)
	(anonymous function) (resources:32:546718)
	mo (resources:32:506203)
	pa (resources:32:541312)
	Sc (resources:32:558539)
	Sc
	(anonymous function) (resources:32:591182)
	xc (resources:32:555198)
	fc (resources:32:551503)
	fc
	(anonymous function) (resources:32:502963)
	(anonymous function) (resources:32:591182)
	Ji (resources:32:502909)
	Wi (resources:32:502844)
	cc (resources:32:548073)
	enqueueSetState (resources:32:506627)
	(anonymous function) (resources:32:575238)
	(anonymous function) (resources:32:1992597)
	(anonymous function) (resources:32:1991408)
	s (resources:32:1990250)
[Error] TypeError: r.id is not a function. (In 'r.id()', 'r.id' is undefined) — resources:32:1826892
	ia (resources:32:539997)
	(anonymous function) (resources:32:546718)
	mo (resources:32:506203)
	pa (resources:32:541312)
	Sc (resources:32:558539)
	Sc
	(anonymous function) (resources:32:591182)
	xc (resources:32:555198)
	fc (resources:32:551503)
	fc
	(anonymous function) (resources:32:502963)
	(anonymous function) (resources:32:591182)
	Ji (resources:32:502909)
	Wi (resources:32:502844)
	cc (resources:32:548073)
	enqueueSetState (resources:32:506627)
	(anonymous function) (resources:32:575238)
	(anonymous function) (resources:32:1992597)
	(anonymous function) (resources:32:1991408)
	s (resources:32:1990250)
[Error] Unhandled Promise Rejection: TypeError: e.dependencies is not a function. (In 'e.dependencies()', 'e.dependencies' is undefined)
	(anonymous function) (resources:32:1991469)
	s (resources:32:1990250)
[Error] WebSocket connection to 'ws://localhost:63343/jb-server-page?reloadMode=RELOAD_ON_SAVE&referrer=%2Fasyncapi%2Frender' failed: The operation couldn’t be completed. Socket is not connected
```

component configuration after template was composed:
```
<html>
<head>
    <!--        <link rel="stylesheet" href="https://unpkg.com/@asyncapi/react-component@1.0.0-next.34/styles/default.min.css">-->
    <link rel="stylesheet" href="http://localhost:63343/asyncapi/resources?resourceUrl=default(1.0.0-next.49).min.css">
</head>
<body>
<div id="asyncapi"></div>

<!--        <script src="https://unpkg.com/@asyncapi/react-component@1.0.0-next.34/browser/standalone/index.js"></script>-->
<script src="http://localhost:63343/asyncapi/resources?resourceUrl=index(1.0.0-next.49).js"></script>
<script>
    AsyncApiStandalone.render({
        schema: {
            url: 'http://localhost:63343/asyncapi/resources?schemaUrl=/private/var/folders/bb/zdnfkz2126s5xcrc57n0j2tw0000gn/T/jasyncapi-idea-plugin-1693522102721.yaml',
            options: {method: "GET", mode: "cors"},
        },
        config: {
            show: {
                sidebar: true,
            }
        },
    }, document.getElementById('asyncapi'));
</script>
<!-- WebSocket connection listening for reload message -->
<script>
    // WebSocket
</script>

</body>
</html>
```

**Comment by jonaslagoni** [comment]
Similar problem yea, just not related to html template 😄 

I should have a fix soon 😅

**Comment by seeren** [comment]
The same here,

Error occurs with .lock update to `3.0.0-next-major-spec.2`

Using `nestjs-asyncapi` integration

```bash
TypeError: message.id is not a function
```

**Comment by jonaslagoni** [comment]
Should be fixed with the recent version, can you check if it still occurs?

**Comment by Pakisan** [comment]
> Should be fixed with the recent version, can you check if it still occurs?

Renders as expected test specs. I checked rendering on `react-component@1.0.0-next.54/` and `react-component@1.2.9/`

Is it ok, that in new versions of component I see blank page instead of errors?

<img width="1627" alt="image" src="https://github.com/asyncapi/asyncapi-react/assets/3388414/3214fd2a-20a5-4434-8372-af329fc2712a">

**Comment by jonaslagoni** [comment]
@Pakisan please create a new bug report 😄 Most likely error is that the plugin is using a wrong parser dependency version. But might be something else, dont know the context

**Comment by derberg** [comment]
seems to be fixed

please create a new issue if not, with results of error using latest react component
