### ISSUE TITLE
Uncaught TypeError: r3.variables is not a function (1.0.0-next.49)

### ISSUE THREAD

**Issue by acelaya** [asyncapi/asyncapi-react#751]
**Description**

After updating to v1.0.0-next.49, there's a crash with the next error:

```
index.js:32 Uncaught TypeError: r3.variables is not a function
    at wr (index.js:32:1769854)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)

Uncaught TypeError: s2.isSend is not a function
    at index.js:32:1789810
    at Array.forEach (<anonymous>)
    at ii (index.js:32:1789769)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)

Uncaught TypeError: n3.title is not a function
    at ei (index.js:32:1782494)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)

Uncaught TypeError: e4.dependencies is not a function
    at e3.getDependentSchemas (index.js:32:1756843)
    at yr (index.js:32:1760864)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)

Uncaught TypeError: r3.variables is not a function
    at wr (index.js:32:1769854)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)

Uncaught TypeError: s2.isSend is not a function
    at index.js:32:1789810
    at Array.forEach (<anonymous>)
    at ii (index.js:32:1789769)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)

Uncaught TypeError: n3.title is not a function
    at ei (index.js:32:1782494)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)

Uncaught TypeError: e4.dependencies is not a function
    at e3.getDependentSchemas (index.js:32:1756843)
    at yr (index.js:32:1760864)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)

The above error occurred in the <wr> component:

    at wr (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:52902:23)
    at li
    at ul
    at section
    at xr (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:52908:20)
    at div
    at div
    at div
    at section
    at pi (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:53271:23)
    at n3 (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:53424:25)
    at n3 (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:55298:25)
    at div
    at AsyncApiContainer (http://localhost:3000/src/components/AsyncApiContainer.tsx:24:3)
    at AsyncApiPage (http://localhost:3000/src/pages/AsyncApiPage.tsx:24:3)
    at RenderedRoute (http://localhost:3000/node_modules/.vite/deps/chunk-36AHSN2H.js?v=373754b6:3324:5)
    at Routes (http://localhost:3000/node_modules/.vite/deps/chunk-36AHSN2H.js?v=373754b6:3777:5)
    at div
    at div
    at Layout (http://localhost:3000/src/components/Layout.tsx:22:3)
    at Router (http://localhost:3000/node_modules/.vite/deps/chunk-36AHSN2H.js?v=373754b6:3724:15)
    at BrowserRouter (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=9a2243e8:300:5)
    at App (http://localhost:3000/src/components/App.tsx:25:22)

The above error occurred in the <ii> component:

    at ii (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:53238:20)
    at div
    at div
    at div
    at section
    at pi (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:53271:23)
    at n3 (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:53424:25)
    at n3 (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:55298:25)
    at div
    at AsyncApiContainer (http://localhost:3000/src/components/AsyncApiContainer.tsx:24:3)
    at AsyncApiPage (http://localhost:3000/src/pages/AsyncApiPage.tsx:24:3)
    at RenderedRoute (http://localhost:3000/node_modules/.vite/deps/chunk-36AHSN2H.js?v=373754b6:3324:5)
    at Routes (http://localhost:3000/node_modules/.vite/deps/chunk-36AHSN2H.js?v=373754b6:3777:5)
    at div
    at div
    at Layout (http://localhost:3000/src/components/Layout.tsx:22:3)
    at Router (http://localhost:3000/node_modules/.vite/deps/chunk-36AHSN2H.js?v=373754b6:3724:15)
    at BrowserRouter (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=9a2243e8:300:5)
    at App (http://localhost:3000/src/components/App.tsx:25:22)

The above error occurred in the <ei> component:

    at ei (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:53208:23)
    at li
    at ul
    at section
    at si (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:53247:20)
    at div
    at div
    at div
    at section
    at pi (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:53271:23)
    at n3 (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:53424:25)
    at n3 (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:55298:25)
    at div
    at AsyncApiContainer (http://localhost:3000/src/components/AsyncApiContainer.tsx:24:3)
    at AsyncApiPage (http://localhost:3000/src/pages/AsyncApiPage.tsx:24:3)
    at RenderedRoute (http://localhost:3000/node_modules/.vite/deps/chunk-36AHSN2H.js?v=373754b6:3324:5)
    at Routes (http://localhost:3000/node_modules/.vite/deps/chunk-36AHSN2H.js?v=373754b6:3777:5)
    at div
    at div
    at Layout (http://localhost:3000/src/components/Layout.tsx:22:3)
    at Router (http://localhost:3000/node_modules/.vite/deps/chunk-36AHSN2H.js?v=373754b6:3724:15)
    at BrowserRouter (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=9a2243e8:300:5)
    at App (http://localhost:3000/src/components/App.tsx:25:22)

The above error occurred in the <yr> component:

    at yr (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:52814:43)
    at div
    at div
    at div
    at oi (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:53253:23)
    at li
    at ul
    at section
    at ai (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:53256:20)
    at div
    at div
    at div
    at section
    at pi (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:53271:23)
    at n3 (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:53424:25)
    at n3 (http://localhost:3000/node_modules/.vite/deps/@asyncapi_react-component_browser.js?v=fb5a2c16:55298:25)
    at div
    at AsyncApiContainer (http://localhost:3000/src/components/AsyncApiContainer.tsx:24:3)
    at AsyncApiPage (http://localhost:3000/src/pages/AsyncApiPage.tsx:24:3)
    at RenderedRoute (http://localhost:3000/node_modules/.vite/deps/chunk-36AHSN2H.js?v=373754b6:3324:5)
    at Routes (http://localhost:3000/node_modules/.vite/deps/chunk-36AHSN2H.js?v=373754b6:3777:5)
    at div
    at div
    at Layout (http://localhost:3000/src/components/Layout.tsx:22:3)
    at Router (http://localhost:3000/node_modules/.vite/deps/chunk-36AHSN2H.js?v=373754b6:3724:15)
    at BrowserRouter (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=9a2243e8:300:5)
    at App (http://localhost:3000/src/components/App.tsx:25:22)

Uncaught TypeError: r3.variables is not a function
    at wr (index.js:32:1769854)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
    at performSyncWorkOnRoot (react-dom.development.js:26096:20)
```

Rolling back to v1.0.0-next.48 fixes the problem.

**Expected result**

No error. Everything keeps working as in 1.0.0-next.48

**Actual result**

The error above

**Steps to reproduce**

1. Clone https://github.com/shlinkio/shlink-api-spec-ui
2. Edit `package.json` and set `@asyncapi/react-component` to `1.0.0-next.49`.
3. Run `npm i`
4. Run `npm run start`.
5. Visit http://localhost:3000/async-api

You should see the error above in browser console.

**Troubleshooting**

Roll back to previous version
